### PR TITLE
Version from version.py, etc.

### PR DESCRIPTION
**Pull request by markuskramerIgitt**
Improvements:
 - Use salt/salt/version.py to retrieve version. 
   - Requires PR https://github.com/saltstack/salt/pull/39274
   - See issue https://github.com/markuskramerIgitt/salt-windows-msi/issues/49 
 - Folder permissions are now set explicitly, but not changed to previous behavior.
 - Physical memory is tested.
 - Documentation and renaming.

### CODE REVIEW

**Comment by markuskramerIgitt** [comment]
Hi @twangboy,
could you please review this PR?

I was contacted by someone who downloaded the (outdated) saltstack salt-windows-msi repository.

Thank you,
Markus

**Comment by markuskramerIgitt** [comment]
Thank you, today I asked a colleague to prepare the mass rollout. 
The location `c:\salt` is not an issue for us.

Neither is vcredist2008.
How do you test the absence of vcredist2008?
I would like to first test, and install vcredist2008 only if missing.
I have no such test.

I think that from Vista on, vcredist2008 is no longer visible at "add remove programs", but the routines are present as a part of Windows.

**Comment by twangboy** [comment]
They're not on my Windows Server 2008R2 vanilla install.

To detect if it's installed we look for two GUIDs, one for 64bit and the other 32. We use the MsiQueryProductStateA system call. See code in the `.nsi` file here:
https://github.com/saltstack/salt/blob/develop/pkg/windows/installer/Salt-Minion-Setup.nsi#L195

And here:
https://github.com/saltstack/salt/blob/develop/pkg/windows/installer/Salt-Minion-Setup.nsi#L439

We get the package from here:
https://www.microsoft.com/en-us/download/details.aspx?id=26368

**Comment by markuskramerIgitt** [comment]
Hi @twangboy, 
good pointers, thank you.

Integrating VC 2008 MFC into the msi is not going to be easy.
Because an msi cannot integrate *.exe, I must use *.msm (merge modules) ([see issue #18](https://github.com/markuskramerIgitt/salt-windows-msi/issues/18)).

One problem is where to store them.
I guess I should not upload them into Github, and their place could be at repo.saltstack.com/windows/dependencies.

Would you store the VC 2008 MFC merge modules on repo.saltstack.com?

Do you want to retrieve them yourself or shall I send them to you?
I found them only in Visual Studio 2008 SP1.

**Comment by twangboy** [comment]
If you want to send them to me, I can put them up. Are you sure they're the MFC version of VCRedist?

**Comment by markuskramerIgitt** [comment]
Pretty sure - as they are called Microsoft_VC90_MFC_x86.msm and Microsoft_VC90_MFC_x86_x64.msm.

How shall I send them to you?

**Comment by markuskramerIgitt** [comment]
Hi @twangboy,
I tested the VC90_MFC_x86_x64 merge module on a (vanilla) Windows Server 2008:
- The dll is installed (see below)
- The log file contains many details

The code is commented out, until the merge modules are on repo.saltstack.com/windows/dependencies 32|64

Before installation
```
C:\>dir /s m*90.dll
File Not Found
```

After installation
```
C:\>dir /s m*90.dll
 Directory of C:\salt\bin\Lib\site-packages\pythonwin

27.01.2017  22:34         1.671.160 mfc90.dll
27.01.2017  22:34            67.072 mfcm90.dll

 Directory of C:\Windows\winsxs\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_951ab4128654b0c9

19.02.2017  14:00         5.086.712 mfc90.dll
19.02.2017  14:00            67.072 mfcm90.dll
```

**Comment by twangboy** [comment]
You can email them to me
slee@saltstack.com

**Comment by markuskramerIgitt** [comment]
Hi @twangboy,
when would you like to accept this change request? 

I can only think of two open topics that should not prevent acception:
 - A security update of CRT is not neccesary [according to Steve Dower of Python](http://bugs.python.org/issue29740). 
 - Neither Python nor Salt need MFC. mfc.dll. can be deleted from the Salt installer. By looking into the details, I found Salt references into a GUI section of Pywin32, but [this could be refactored](https://github.com/pywin32/pypiwin32/issues/60).

**Comment by twangboy** [comment]
@markuskramerIgitt Sorry... this one slipped through the cracks. Thanks for following up.

**Comment by markuskramerIgitt** [comment]
Hi @twangboy,
with the above commit, xoviat moves the only win32gui-function that Salt uses into win32api.
This will enable us to use Pywin32 without MFC.dll.

How do you prefer to use Pywin32 without win32gui?
 - Create a Pywin32 wheel without win32gui ([started here](https://github.com/pywin32/pypiwin32/commit/703b6d144d8fb5a60bda153268d2ed19e01153cb))
 - Build Salt with the sources of Pywin32.

**Pull request merged**
