### PR TITLE
Fix hintpath to wix.dll

### PR DESCRIPTION
**Pull request by berkut-174**

### CODE REVIEW

**Comment by markuskramerIgitt** [comment]
@berkut-174 I like the use of variables.

I believe $(ProgramFiles) becomes either
  `c:\Program Files (x86)` or
  `c:\Program Files`

depending on you OS being 32 or 64.

If that is the case, then only one HINT is enough.

I have no 32bit Windows at hand. Could you please test or comment?

**Comment by berkut-174** [comment]
No, `$(ProgramFiles)` becomes `C:\Program Files`
On a OS 32-bit, everything is fine.
`$(ProgramFiles) (x86)` is needed just for OS 64-bit, since:
```
> sigcheck64.exe wix311.exe

Sigcheck v2.73 - File version and signature viewer
Copyright (C) 2004-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

wix311.exe:
        Verified:       Signed
        Signing date:   10:39 17.09.2019
        Publisher:      WiX Toolset (.NET Foundation)
        Company:        .NET Foundation
        Description:    WiX Toolset v3.11.2.4516
        Product:        WiX Toolset v3.11.2.4516
        Prod version:   3.11.2.4516
        File version:   3.11.2.4516
        MachineType:    32-bit
```

**Comment by berkut-174** [comment]
The hintpath is currently invalid. It must either be relative `\..\..\..\..\..\Program Files\WiX Toolset v3.11\bin\wix.dll` or represent a variable, for example `$(ProgramFiles)`. Well, or `wix.dll` should be in `C:\Salt-Dev\salt-windows-msi\wix.d\MinionConfigurationExtension\bin\Release\`.
I had this problem when building the package for the first time. At least in VS 2019.

**Comment by markuskramerIgitt** [comment]
@berkut-174 - I was not able to access my computer for the last days. 

I confirm the current master branch contains a invalid hintpath and your changes fix that issue

I tested on 64bit Windows and therefore merge.
 
Thank you for contributing!!!

Do you have other suggestions or remarks?

**Comment by markuskramerIgitt** [comment]
The orginal HintPath is from an msi expert:

    <HintPath>$(MSBuildExtensionsPath)\..\WiX Toolset v3.9\bin\wix.dll</HintPath>

I changed to a higher version but (not being an expert) removed the variable:

    <HintPath>c:\Program Files (x86)\WiX Toolset v3.11\bin\wix.dll</HintPath>

Would the single line

    <HintPath>$(MSBuildExtensionsPath)\..\WiX Toolset v3.11\bin\wix.dll</HintPath>

be serving both 32 and 64bit?

**Comment by markuskramerIgitt** [comment]
I just tested this HintPath on 64-bit

          <HintPath>$(Wix)bin\wix.dll</HintPath>

I am very confident this also works on 32-bit Windows
Could you please test on 32-bit Windows?

**Comment by berkut-174** [comment]
> ```
>       <HintPath>$(Wix)bin\wix.dll</HintPath>
> ```
> Could you please test on 32-bit Windows?

Yes, this option works on both OS — 32 & 64.

I also checked again and found out that it is enough to specify only one hintpath:
```
<HintPath>$(ProgramFiles)\WiX Toolset v3.11\bin\wix.dll</HintPath>
```
This also works correctly on both OS. No errors were noticed.
Thank!

**Comment by markuskramerIgitt** [comment]
Thank your for testing!

As you tested `<HintPath>$(Wix)\bin\wix.dll</HintPath>`, and this requires no updates for future WiX releases, would you like to open a OR for it? Otherwise I will.

**Comment by berkut-174** [comment]
I can make a new pull request with `<HintPath>$(Wix)\bin\wix.dll</HintPath>`.
Confirm if necessary.

**Comment by markuskramerIgitt** [comment]
Yes, kindly replace all 4 occurrences of `$(ProgramFiles)` by 3 times `$(Wix)`:
- for HintPah
- for logging (2 times)

**Pull request merged**
