### PR TITLE
ssm (Salt Service Manager) replaced nssm

### PR DESCRIPTION
**Pull request by markuskramerIgitt**
ssm (Salt Service Manager) replaced nssm
Suppress ICE03 when linking a msm (Merge Module)
Added install_required_software.cmd

### CODE REVIEW

**Comment by markuskramerIgitt** [comment]
Hi @twangboy, have you noted this pull request?

**Comment by twangboy** [comment]
@markuskramerIgitt Do you want me to merge this?

Also, there are some other changes we've made to the NSIS installer you may need be aware of. We were having problems the vcredist 2015 in the Py3 installer. In some instances the host ended up with a corrupted installation of vcredist and the minion would fail to start as a result. Upon further investigation we found that Py3 doesn't need the vcredist as it ships with the vcredist dll in the python directory, so that has been removed from Py3 installers.

I'm also going to be working on allowing salt to be installed anywhere, but default to the Program Files directory. I was thinking we could place the config in the ProgramData directory as you've been doing. Regardless of where salt is installed. Treat it like we do `c:\salt\conf`. Then you wouldn't have to guess where the config files are located.

**Comment by markuskramerIgitt** [comment]
Yes @twangboy, please merge this pull request, and thank you for approval.

Regarding installing salt anywhere:
The msi installer only reads & places configuration from & to the single file `c:\salt\conf\minion`. 

Please be aware of a security constraint: only administrators must be able to set the name and the public key of the salt-master. Therefore, access to `minion`, `minion.d` and the public key of the master must be highly restricted.
`ProgramData` has open access for all users (it is an alias for `c:\users\Public`) and therefore is unsuitable.

I will rework and move the misleading and flawed `idea_KEEP_CONFIG.md`, which wrongly mentions ProgramData, into a feature request.

**Comment by twangboy** [comment]
So, maybe keep the config in the path relative to the salt installation then. Ie, `C:\Program Files\salt\config`

**Comment by markuskramerIgitt** [comment]
I think `C:\Program Files\salt\config` is a good place.

**Pull request merged**
