### PR TITLE
Replace_1_with_True_for_YAML

### PR DESCRIPTION
**Pull request by markuskramerIgitt**
Consistent use of True or False in Python and 1 or "" in msi.

### CODE REVIEW

**Comment by xeacott** [comment]
Correct me if I'm wrong, but throughout the code base and what we allow the user to set as optional arguments, are the uses of `strings`, `ints`, and `bools` being used interchangeably?

And for this comments being added:
`// Read SaltKey properties and convert some from 1 to True or to False` are we converting the python singleton objects to be evaluated as strings `True` and `False`?

**Comment by markuskramerIgitt** [comment]
msi properties (more correctly [Windows Installer properties](https://docs.microsoft.com/en-us/windows/win32/msi/properties)) have only one type: strings. There is no other type.

I see that the use of `1` for __TRUE__ and `""` (empty string) for __FALSE__ in the msi installer is confusing.

The Windows installer demands the latter: the empty string (void) is the only expression allowed for __FALSE__. All other values are __TRUE__, so there is a liberty.

Using 1 is confusing because 1 looks like a number and user could believe that 0 is the value for __FALSE__. Unfortunately, 0 --- as msi property --- is __TRUE__

I come to the conclusion that the use of `X` and`""` is less confusing, because this how a check mark works: either there is a check mark or there is not. 

The comment refers to YAML. The config files are YAML. YAML uses the strings True and False:

    minion_id_caching: True
    minion_id_caching: False

Therefore the msi properties must be converted.

I don't see a relation to Python (or  python singleton objects).

Did I get your questions right?

**Comment by xeacott** [comment]
Yes, I understand and that was me interpreting things incorrectly. The clarification answered my questions, thanks :) 

I also agree that having a single convention for the MSI installer to evaluate things as True or False is important. It also can mean clearer documentation as to what the user reads and understands.

**Comment by markuskramerIgitt** [comment]
Good.

Could you please merge? I will create a new PR for user input of True and False values

**Comment by xeacott** [comment]
Merged.

**Comment by markuskramerIgitt** [comment]
Thanks.
Could you please merge or comment 2 more PR?

**Pull request merged**
